### ISSUE TITLE
Tag "<asset:script/>" is eating the content.

### ISSUE THREAD

**Issue by aadrian** [bertramdev/asset-pipeline#111]
The tag ```<asset:script/>``` seems to eat it's content with Grails 2.x (and the latest version of this plug-in).

How to reproduce: use several ```<asset:script/>``` tags across the parts that made up a page. Those JS lines won't be present in the final page, thus rendering this tag useless :(.

**Comment by davydotcom** [comment]
This is for deferred scripts you need the final deferred script tag to render them please look here.

http://www.asset-pipeline.com/manual/index.html#taglibs-2

**Comment by aadrian** [comment]
> This is for deferred scripts you need the final deferred script tag to render them please look here.

Thank you for the information.

IMHO however when not using the deferred tag, the snippets should not be eaten, but rendered simply in the page at their position, so that even if the content is not optimized, at least it's not broken.

**Comment by davydotcom** [comment]
Technically not possible because you don’t know wether that script is written until after the output writer has completed or not. It is how gsp render works. Technically I do not even recommend using asset:script that is solely there to facilitate migration from the resources plugin and its use of r:script which does the same thing.

**Comment by aadrian** [comment]
Thank you for your help.

The plug-in page: https://grails.org/plugin/asset-pipeline links to a different/older documentation.
Other users might also find http://www.asset-pipeline.com/ interesting.
