### ISSUE TITLE
AngularJs Error 'Uncaught TypeError: b._asset_pipeline_require is not a function'

### ISSUE THREAD

**Issue by muusaebaer** [bertramdev/asset-pipeline#118]
I use the asset-pipeline plugin 2.11.1 together with less-asset-pipeline 2.11.1 and angular-annotate-asset-pipeline:2.4.1 inside a Grails 3.1.10 application with angularJs 1.5.8. When I load my app inside the browser I get the following error:

Uncaught TypeError: b._asset_pipeline_require is not a function

My gradle configuration looks like this:

` 
    assets  {
        minifyJs = false
        minifyCss = true
        enableSourceMaps = false

        configOptions = [
            less: [
                compiler: 'standard'
           ]
    ] //useful for custom config on extension libraries

    minifyOptions = [
            languageMode: 'ES5',
            targetLanguage: 'ES5',
            optimizationLevel: 'SIMPLE',
            angularPass: true // Can use @ngInject annotation for Angular Apps
    ]

    includes = []
    excludes = ["**/*.less", "**/src/*.js",  "**/<src/**/*.js", "**/docs/**", "**/tests/**", "**/vendor/**", "**/src/**", "**/*.gz"]//Example Exclude GLOB pattern

    //for plugin packaging
    packagePlugin=false //set to true if this is a library

    //developmentRuntime can be turned off
    developmentRuntime=true

    //if you want to customize the jar task this task runs on you can specify a jarTaskName
    //    jarTaskName=null

    // Can add custom asset locations (directories or individual jar files)
    from 'webjars/**'
    //    from '/path/to/file.jar'
    }`

It get the error no matter if I switch minifyJs, minifyCss and enableSourceMaps on or off.

Any ideas how to fix this?

**Comment by amcclain** [comment]
Just ran into what I believe is the same underlying issue, although not with Angular.  We're updating our app to use the latest pipeline 2.11.1.

On of our projects uses the popular [clipboard.js library](https://clipboardjs.com/), which we include by simply adding [its dist file](https://github.com/zenorocha/clipboard.js/blob/master/dist/clipboard.js) to our assets. Asset Pipeline's JsRequireProcessor looks at this file and ends up replacing the various require() calls with _asset_pipeline_require()s.  However it never inserts the implementation of that method from this file, so it's undefined.

It's not clear to me exactly how the code is triggered that should be inserting the stub definition, but looking at the source for this clipboard library, I see that the `require()` calls are within nested functions that have `require` passed as a local variable, so it's presumably getting various implementations depending on the environment in which its run, and none / not all of those are suitable for replacement by whatever asset pipeline is trying to do with its intercepted implementation.

I don't know if this is a standard pattern, but I believe all the (convoluted) code in the linked dist file is output by an NPM build of the file, so it might be the kind of issue that's widespread.  Looking at the asset pipeline code, however, I couldn't find any way to short-circuit or otherwise customize the scanning of JS source for requires() statements.  Given our environment, we would never use a standard node require() and therefore don't want any of this processing to take place at all.

**Comment by amcclain** [comment]
The regex for grabbing and modifying requires statements seems likely to be overly eager in other ways as well - for instance, we make heavy use the ExtJS library, which has a core method `Ext.require()` that can take a string class name as an argument - e.g. `Ext.require('Ext.panel.Panel')`, which would be incorrectly modified by this processor to `Ext._asset_pipeline_require('Ext.panel.Panel')` which is going to be an issue....

**Comment by andersb** [comment]
I'm seeing the same type of behavior with Angular 2.

I'm using IntelliJ 2016.2.2 and configured it to compile typescripts.
So, both .ts and .js files will end up in /assets/typescript/**

The problem is that a line of code like 
var core_1 = require('@angular/core');

will be processed to
var core_1 = _asset_pipeline_require('@angular/core');

I also tried to exclude all files in typescripts-directory but that didn't work either.

For now, going back to assets-pipeline 2.9.1 will make things work because then the require-keyword isn't replaced but that isn't really a long term solution.

**Comment by davydotcom** [comment]
try with 2.11.2

**Comment by andersb** [comment]
I still have the same problem.
Trying to figure out if I'm doing something else wrong.

**Comment by amcclain** [comment]
The latest 2.11.2 update appears to be working well for us, thank you. The instances of `require()` that happen to be in our codebase are no longer being touched or transformed. 👍

**Comment by muusaebaer** [comment]
For me 2.11.2 also resolved the issue.
