### ISSUE TITLE
Support for Brotli Content-Encoding

### ISSUE THREAD

**Issue by davidkron** [bertramdev/asset-pipeline#171]
The newest versions of almost all major browsers are now supporting the new Content-Encoding algorithm "Brotli".

There should be an option in the asset-pipeline to also generate files pre-encoded files for Brotli, just like the gzip variant.

**Comment by YSakhno** [comment]
Hello @davidkron, I'd like to inform you (and everyone else reading this) that I've just committed into [my own repository](https://github.com/YSakhno/asset-pipeline-compress) my preliminary work on the plugin that does just what you ask! Well, it does at least the 'pre-encoding' part of Brotli compression... It has a dependency on an external library (which is not very easily integrated), so that's why the decision to make it a separate repo rather than making a pull-request here.

I still have to figure out how to publish my code into Maven repos and fix some oversights here and there, this is still pretty much a work-in-progress so stay tuned!

**Comment by davydotcom** [comment]
if you guys wait a bit the google brotli library has a new BrotliOutputStream in 0.2.0-SNAPSHOT. as soon as they publish 0.2.0 to maven asset-pipeline is ready to go. Ive already done the leg work on adjusting the compiler and filters

**Comment by YSakhno** [comment]
I am sorry, which library is that?

**Comment by davidkron** [comment]
Closing stale issue.
