### ISSUE TITLE
CachingLinkGenerator does not cache

### ISSUE THREAD

**Issue by ingokegel** [bertramdev/asset-pipeline#221]
The current implementation

	String resource(Map attrs) {
		def url = asset(attrs)
		if(!url) {
			url = super.resource(attrs)
		}
		return url
	}

always consults all resolvers and never caches the URL. It should be changed to

	String resource(Map attrs) {
		def url = super.resource(attrs)
		if(!url) {
			url = asset(attrs)
		}
		return url
	}

**Comment by davydotcom** [comment]
We always want to check for the asset-pipeline copy first.

**Comment by davydotcom** [comment]
in war mode asset pipeline actually has its own cache resolution so its fairly quick as well.

**Comment by ingokegel** [comment]
The performance in dev mode is really bad and I'm trying to find out what can be done about it. All my calls to linkGenerator.resource() which are not asset-related go through all resolvers. That adds half a second to each request. If that was at least cached, but it's done every time.

**Comment by davydotcom** [comment]
Well CachingLinkGenerator is not even used in dev mode its only initialized in grails-core in warDeployed mode. Ill look into speeding up the resolver cycle, what version are you running?
--
David Estes

On February 2, 2015 at 7:49:56 AM, ingokegel (notifications@github.com) wrote:

The performance in dev mode is really bad and I'm trying to find out what can be done about it. All my calls to linkGenerator.resource() which are not asset-related go through all resolvers. That adds half a second to each request. If that was at least cached, but it's done every time.

**Comment by ingokegel** [comment]
2.1.1, and CachingLinkGenerator is used when I inject 

    def linkGenerator

into a taglib. That it probably unintended,

**Comment by davydotcom** [comment]
What grails version? Hmm maybe it does try turning a config off: 

Below is the code in question that determines which link generator to use
```groovy
        def cacheUrls = application.config?.grails.web?.linkGenerator?.useCache
        if(!(cacheUrls instanceof Boolean)) {
            cacheUrls = true
        }


        grailsLinkGenerator(cacheUrls ? CachingLinkGenerator : LinkGenerator, serverURL) { bean ->
            bean.autowire = true
        }
```

**Comment by ingokegel** [comment]
I'm using grails 2.4.4. 

Your LinkGenerator does the same thing. It's just that the link generator is too inefficient. There are a lot of resolvers and for each plugin there is a separate resolver. Below you see 30 links that have to be generated for one page and it turns into 720 slow resolutions, because most of them are not for assets and all resolvers are queried.

![2015-02-02_14-06-38](https://cloud.githubusercontent.com/assets/1199475/6000999/279f53ba-aae5-11e4-8255-2b9ffe30bc06.png)

SpringResourceAssetResolver is especially slow, as you can see, because it invokes ClassLoader.getResource(). If I trim the resolves manually with something like 

     AssetPipelineConfigHolder.resolvers = AssetPipelineConfigHolder.resolvers.findAll {
       it instanceof FileSystemAssetResolver && it.baseDirectory.path.startsWith('grails-app')}

in Bootstrap.groovy, I get acceptable performance, but that is just a hack.

**Comment by davydotcom** [comment]
Ah the class path resolver is new … Thats probably why this came up. It adds support for scanning binary plugins. I think we can probably improve that resolver to be cached.
--
David Estes

On February 2, 2015 at 8:16:35 AM, ingokegel (notifications@github.com) wrote:

I'm using grails 2.4.4.

Your LinkGenerator does the same thing. It's just that the link generator is too inefficient. There are a lot of resolvers and for each plugin there is a separate resolver. Below you see 30 links that have to be generated for one page and it turns into 720 slow resolutions, because most of them are not for assets and all resolvers are queried.



SpringResourceAssetResolver is especially slow, as you can see, because it invokes ClassLoader.getResource(). If I trim the resolves manually with something like

 AssetPipelineConfigHolder.resolvers = AssetPipelineConfigHolder.resolvers.findAll {
   it instanceof FileSystemAssetResolver && it.baseDirectory.path.startsWith('grails-app')}

in Bootstrap.groovy, I get acceptable performance, but that is just a hack.

**Comment by davydotcom** [comment]
Just to  clarify it is not 1 resolver per plugin. It is 1 resolver per source based plugin (file system based which should be quick). Plus 3 class path resolvers scanning 3 different resolver paths. META-INF/static, META-INF/assets, META-INF/resources for binary plugins.
--
David Estes

On February 2, 2015 at 8:18:44 AM, David Estes (davydotcom@gmail.com) wrote:

Ah the class path resolver is new … Thats probably why this came up. It adds support for scanning binary plugins. I think we can probably improve that resolver to be cached.
--
David Estes

On February 2, 2015 at 8:16:35 AM, ingokegel (notifications@github.com) wrote:

I'm using grails 2.4.4.

Your LinkGenerator does the same thing. It's just that the link generator is too inefficient. There are a lot of resolvers and for each plugin there is a separate resolver. Below you see 30 links that have to be generated for one page and it turns into 720 slow resolutions, because most of them are not for assets and all resolvers are queried.



SpringResourceAssetResolver is especially slow, as you can see, because it invokes ClassLoader.getResource(). If I trim the resolves manually with something like

 AssetPipelineConfigHolder.resolvers = AssetPipelineConfigHolder.resolvers.findAll {
   it instanceof FileSystemAssetResolver && it.baseDirectory.path.startsWith('grails-app')}


in Bootstrap.groovy, I get acceptable performance, but that is just a hack.

**Comment by davydotcom** [comment]
I have a solution to this now. gonna take a me a bit to finish though , give me a day or 2

**Comment by ingokegel** [comment]
Sounds good, I'll be happy to test it!

**Comment by davydotcom** [comment]
Ok 2.1.2 now caches the classpath resolution. Things should be faster now
