### ISSUE TITLE
Assets in WAR files

### ISSUE THREAD

**Issue by JBSants** [bertramdev/asset-pipeline#232]
Hi,

I've just wrote a binary plugin in order to modularize my app. It works fine in run-app, but when I run or create a war the plugin assets do not get packaged correctly.

**Comment by davydotcom** [comment]
Can you give me some version information. Which version of Asset-Pipeline and grails? also which version of AP was in your plugin?
--
David Estes

On March 6, 2015 at 10:53:36 AM, João Santos (notifications@github.com) wrote:

Hi,

I've just wrote a binary plugin in order to modularize my app. It works fine in run-app, but when I run or create a war the plugin assets do not get packaged correctly.

**Comment by JBSants** [comment]
I use asset-pipeline 2.1.4 both in my app and plugin and I use grails 2.4.4

**Comment by thomasguo** [comment]
Hi David,  I have the same problem.  I am using  JDK7, Grails 2.4.4 and asset-pipeline 2.1.3(also tried 2.1.5).   Please help.

**Comment by davydotcom** [comment]
can we get a sample project going maybe?

**Comment by thomasguo** [comment]
Yes, that's a good idea.  I suppose we will need 2 sample projects. One for a binary plugin and the other for a normal application project which uses that plugin.  Let me know if I can help.

**Comment by JBSants** [comment]
Here are the 2 sample projects. If you run-app the assets work fine. You can check by pressing the button in the main page. But, if you run-war the assets don't work.

https://drive.google.com/file/d/0B34PIffi4jk_SHVfTUR4R0pJR1k/view?usp=sharing
https://drive.google.com/file/d/0B34PIffi4jk_bzZ4aVVScTZQZUk/view?usp=sharing

**Comment by thomasguo** [comment]
Hi guys,  any updates for this issue?

**Comment by davydotcom** [comment]
Woohoooo!! Figured this out last night and this morning with help from @graemerocher . Sorry for the delay but try out 2.2.1

**Comment by thomasguo** [comment]
Thank you very much. It works greatly.  I use 2.2.2 .

**Comment by mugren** [comment]
Hi,
I've encountered interesting situation today. 
I have one small app in Grails 2.5.0 that required some changes to be done. I've noticed that there is new version of the assets plugin and upgraded from 2.1.5 to 2.3.8. Since that the assets weren't packaged in the war (precompiling assets step didn't log anything), assets folder only contains manifest file.
Tried to do downgrading to 2.1.5 but for some funky reason it didn't worked again.
After I read this section, tried the 2.2.2 version of the plugin and now it works fine.

If it means something:
dependencies {
        compile ('c3p0:c3p0:0.9.1.2')
        compile ('org.apache.derby:derby:10.6.1.0')
        compile ('org.apache.derby:derbyclient:10.6.1.0')
        compile ('quartz:quartz:1.5.2')
        compile ('javax.mail:mail:1.4.1')
        compile ('org.apache.poi:poi:3.6')
        compile ('commons-lang:commons-lang:2.6')
        compile ('commons-collections:commons-collections:3.2')
        compile ('commons-codec:commons-codec:1.2')
    }

    plugins {
        // plugins for the build system only
        build ":tomcat:7.0.55.2"

        // plugins for the compile step
        compile ":scaffolding:2.1.2"
//        compile ":asset-pipeline:2.3.9"
        compile ":asset-pipeline:2.2.2"
        compile ":spring-security-core:2.0-RC5"
        compile ":json-exclusion-marshaller:0.3"

        // plugins needed at runtime but not for compilation
//      runtime ":hibernate4:4.3.8.1"
        runtime ":hibernate:3.6.10.19"
}

**Comment by davydotcom** [comment]
I published 2.3.8 with a fix
