### ISSUE TITLE
Excludes for plugins using grails-resources approach

### ISSUE THREAD

**Issue by lesiki** [bertramdev/asset-pipeline#258]
I have an app A that depends on two plugins, X and Y. Plugin X has a font file in its web-app/fonts directory, and Plugin Y has a different font file with the same name in its grails-app/assets/fonts folder. The version of the font that I want is the one in Plugin Y's grails-app/assets/fonts folder.

The behaviour I'm seeing is that when I run my app A, a css file from plugin Y (the modern asset-pipeline one) which references that font file gets the version of the file from plugin X. I've confirmed this behaviour by diffing the asset I'm served via the browser with the two plugins' font files. Also, deleting Plugin X's font file from the target directory while the app is running causes the Plugin Y asset to be served.

I've tried disabling the asset using ```grails.assets.plugin."x".excludes =["**/*"]```, and also copied this to _Events.groovy as described in https://github.com/bertramdev/asset-pipeline/issues/111, but the unwanted asset is still always there.

Can the asset pipeline plugin exclude resources from another plugin that used the old web-app setup? If not, can I get it to prefer identically named resources from another plugin?

I'm using asset-pipeline 2.2.0 in Grails 2.4.3.

**Comment by davydotcom** [comment]
If you can provide a test app that would help a bunch here. Typically the way the asset-pipeline works is it flattens the fileset. The plugin creator should always use a subfolder within assets to scope it. This is done as a convenience so that the user of a plugin in an app can always override an asset by putting a file with the same name in their apps 'assets' folder. The asset that is chosen (if there are more than one) is based on the order of the resolver classes. An exclude here probably wont work because and exclude is only adhered to at build time for a war or fatjar. I assume you are seeing this in dev mode yes?

**Comment by lesiki** [comment]
Yes, it happens in both dev and prod modes. From your explanation, I suppose this is more a case of poor/inflexible plugin design than a bug in asset-pipeline. Maybe asset-pipeline could offer a more powerful exclude feature to block plugins' assets in dev mode (including plugins using resources plugin)?
