### ISSUE TITLE
Bugs in HtmlProcessor#isRelativePath(assetPath) 2.3.2

### ISSUE THREAD

**Issue by rgoldberg** [bertramdev/asset-pipeline#262]
I think that there are bugs in version 2.3.2 of `HtmlProcessor#isRelativePath(assetPath)`:

```
private isRelativePath(assetPath) {
    return !assetPath.startsWith("/") && !assetPath.startsWith("http")
}
```

It will consider the following URLs as absolute, when they actually are relative:

```
// http is part of a path name
httpRelativePath

// switching from http protocol to https, but still using relative path
https:relativePath
```

It also will not work for other URL schemes, like ftp, etc.

It would probably be best to change it to:

```
/**
 * A URL is absolute if begins with:
 *
 *     a slash ("/")
 *
 * OR
 *
 *     a scheme directly followed by a slash (e.g., http:/, https:/, ftp:/, etc.)
 *
 * A scheme:
 *
 *     a) starts with a letter (\p{L})
 *
 *     b) which is followed by any combination of letters (\p{L}), digits (\d), pluses ("+"), periods ("."), or hyphens ("-")
 *
 *     c) terminates with a colon (":").
 */
private static final Pattern ABSOLUTE_URL_PATTERN = ~/(?:\/|\p{L}[\p{L}\d+-.]*:[\/]).*/

private isRelativePath(final String assetPath) {
    ! ABSOLUTE_URL_PATTERN.matcher(assetPath).matches()
}
```

Tests:

```
assert ! isRelativePath('/absolute')
assert ! isRelativePath('http:/absolute')
assert ! isRelativePath('ftp:/absolute')

assert isRelativePath('relative')
assert isRelativePath('http')
assert isRelativePath('http:relative')
assert isRelativePath('ftp:relative')
```

Please see the following link for the syntax of URL schemes (sorry if Wikipedia is incorrect; I didn't actually read the referenced RFC spec):

https://en.wikipedia.org/wiki/URI_scheme#Generic_syntax

**Comment by rgoldberg** [comment]
This should also be fixed in `CssProcessor`.

It would probably be useful to create a `Urls` utility class, and to move `isRelativePath` to a new static method in that class, possibly named `isRelative` instead of `isRelativePath`.

**Comment by davydotcom** [comment]
This was actually kept intentionally dumb to minimize overhead in the replace all scan if we can keep it fast then sure

**Comment by davydotcom** [comment]
But agreed we should

**Comment by rgoldberg** [comment]
If you're worried about performance, I started working on a `JavaScriptProcessor` that I copied from your `HtmlProcessor`, but I rewrote it to be more efficient.  e.g., instead of calling `inputText.replaceAll(String, Closure)`, which compiles the same `Pattern` every time, I saved the compiled `Pattern` in a `static final` constant, and use that in a call to `inputText.replaceAll(Pattern, Closure)` instead.

I also rewrote it to be more in my coding style (I find it much easier to code when things are formatted my way; obviously, if you use my `JavaScriptProcessor`, you can change things back...).

I'm relatively new to Grails / Groovy, so some changes might cause performance degradations in Groovy that they wouldn't have caused in Java (e.g., I added actual variable types to all variables, instead of `def`; in Java, that wouldn't slow anything down, but it might in Groovy)

**Comment by davydotcom** [comment]
Actually is faster in groovy to strong type these processors have been on my list to enhance. A PR to core would be most welcome. Lots to do, help is much appreciated .  I also have considered switching regex to Joni library as its 2x faster but maybe for another time

**Comment by rgoldberg** [comment]
I have a few questions about the HtmlProcessor that doesn't directly relate to this issue, but I assume that they aren't bugs at all, so, do you mind if I ask them here?

`HtmlProcessor` has a private method named `relativePath(...), but it's never called.  Should it be called, or deleted?

`HtmlProcessor` only calculates cache digests if `file.compiledExtension != 'html'`.  Why doesn't it calculate cache digests for `.html` files?

The `HtmlProcessor` class JavaDoc says that it works for "relative image paths".  I didn't notice anything that limited URL rewriting to images, so I assume that this is vestigial from copying over from `CssProcessor`, but, maybe I missed something that actually limits the URLs that the `HtmlProcessor` rewrites

In `JavaScriptProcessor`, should I skip cache digests for `.html` files, `.js` files, or any other files?

**Comment by davydotcom** [comment]
1.
That is a legacy method that I actually deleted in my local copy yesterday

2.
Typically html files are scanned by web crawlers and the like. It did not make sense to me to setup a cache busting digest as most browsers don’t typically suffer from needing to cache bust an html page

3. It should work with any file type not just images thats a doc copy issue. There is an open issue that it does not work with double nested relative paths I am going to look into that later today.

4. I would say the only file type you can skip on digest checking is html.


--
David Estes

On June 19, 2015 at 8:24:35 AM, rgoldberg (notifications@github.com) wrote:

I have a few questions about the HtmlProcessor that doesn't directly relate to this issue, but I assume that they aren't bugs at all, so, do you mind if I ask them here?

HtmlProcessor has a private method named `relativePath(...), but it's never called. Should it be called, or deleted?

HtmlProcessor only calculates cache digests if file.compiledExtension != 'html'. Why doesn't it calculate cache digests for .html files?

The HtmlProcessor class JavaDoc says that it works for "relative image paths". I didn't notice anything that limited URL rewriting to images, so I assume that this is vestigial from copying over from CssProcessor, but, maybe I missed something that actually limits the URLs that the HtmlProcessor rewrites

In JavaScriptProcessor, should I skip cache digests for .html files, .js files, or any other files?

**Comment by rgoldberg** [comment]
Thanks.

2. I was thinking of putting my static partial html files on S3,, instead of serving them from my Grails server, to reduce load.  Asset Pipeline inserts cache digests into the names of html files that I put under assets, and doesn't output them without a cache digest in their name.  So, I html assets won't correctly link to other html assets unless:

A. I post-process to remove cache digests from the html file names under assets

B. `HtmlProcessor` inserts the cache digest into html file URLs

C. Asset Pipeline doesn't insert cache digests into the names of html files

I guess that maybe putting html files on S3 might be bad for SEO, and the like, so Maybe I should serve them from my Grails server...  But, if I serve the html files from my Grails server, so they'll be under the `web--app` directory instead of being under the `assets` directory, will `HtmlProcessor` rewrite URLs in the html files when they're not under `assets`?  If not, then it seems like I'm in a Catch-22.

3. What is a double-nested relative path?  Is that like "double secret probation"?

**Comment by davydotcom** [comment]
1. AP already has logic that duplicates digest name files with non digest name files in the grails plugin you’ll see a Bootstrap file that does it. Im not sure what you are using to do your cdn upload. If you are using the cdn-asset-pipeline we need to raise that issue with @benorama since that has changed in 2.2.x and greater.

2.
Referring to issue #261
--
David Estes

On June 19, 2015 at 8:46:27 AM, rgoldberg (notifications@github.com) wrote:

Thanks.

I was thinking of putting my static partial html files on S3,, instead of serving them from my Grails server, to reduce load. Asset Pipeline inserts cache digests into the names of html files that I put under assets, and doesn't output them without a cache digest in their name. So, I html assets won't correctly link to other html assets unless:
A. I post-process to remove cache digests from the html file names under assets

B. HtmlProcessor inserts the cache digest into html file URLs

C. Asset Pipeline doesn't insert cache digests into the names of html files

I guess that maybe putting html files on S3 might be bad for SEO, and the like, so Maybe I should serve them from my Grails server... But, if I serve the html files from my Grails server, so they'll be under the web--app directory instead of being under the assets directory, will HtmlProcessor rewrite URLs in the html files when they're not under assets? If not, then it seems like I'm in a Catch-22.

What is a double-nested relative path? Is that like "double secret probation"?

**Comment by davydotcom** [comment]
Not sure if you knew this but you can also just use gradle to build static sites with asset pipeline and you have more control like :

```groovy
assets {
  enableDigests=true
  skipNonDigests=false
  enableGzip=true
}
```

https://github.com/davydotcom/static-ap-test

--
David Estes

On June 19, 2015 at 8:46:27 AM, rgoldberg (notifications@github.com) wrote:

Thanks.

I was thinking of putting my static partial html files on S3,, instead of serving them from my Grails server, to reduce load. Asset Pipeline inserts cache digests into the names of html files that I put under assets, and doesn't output them without a cache digest in their name. So, I html assets won't correctly link to other html assets unless:
A. I post-process to remove cache digests from the html file names under assets

B. HtmlProcessor inserts the cache digest into html file URLs

C. Asset Pipeline doesn't insert cache digests into the names of html files

I guess that maybe putting html files on S3 might be bad for SEO, and the like, so Maybe I should serve them from my Grails server... But, if I serve the html files from my Grails server, so they'll be under the web--app directory instead of being under the assets directory, will HtmlProcessor rewrite URLs in the html files when they're not under assets? If not, then it seems like I'm in a Catch-22.

What is a double-nested relative path? Is that like "double secret probation"?

**Comment by rgoldberg** [comment]
My `JavaScriptProcessor` won't work because of circular dependencies (even if JavaScript files shouldn't have circular dependencies, there might be circular quoted references in comments between JavaScript files).

To compute the cache digest of a file, all of the relative URLs that it contains must be rewritten to include the cache digest of the referenced file.  If files `a.js` & `b.js` reference each other, then you get an infinite loop attempting to calculate their cache digests.

This problem shouldn't occur for CSS files, since they shouldn't be referencing other CSS files using `url()`.

This problem shouldn't occur for HTML files, since AP doesn't rewrite URLs from HTML files to other HTML files, so they can't have circular dependencies.

Also, there are some times in some of the existing JavaScript in the code I'm working on in which URLs are concatenated from variables, which the `JavaScriptProcessor` won't be able to recognize for URL rewriting.

To avoid these problems, I'll have to not use cache digests in file names.

I'll always use absolute URLs so that they won't ever be rewritten by any AP processors.

What classes must I modify so that my "enableDigests" changes from #259 won't "break the servlet renderer"?

Once I get AP working, I'll make a pull request with my AP changes.

**Comment by rgoldberg** [comment]
Unfortunately, some third-party CSS uses relative URLs, so, in order to not have to modify third-party CSS files, I'll also need to be able to turn off URL rewriting for relative URLs, too.

Is that currently possible?

Sorry that this is veering off the topic of #262, but I didn't want to open a new issue or to revive #259 until checking with you what's already possible.

**Comment by davydotcom** [comment]
Look at the AssetPipelineBootstrap file to see how we copy files out and do non digested named files. On the `JsProcessor` front I was worried about this and is one reason I never try to do asset replacement in javascript land. I normally set global asset vars in the html to pass through to my javascript library if I absolutely need them to be digested. However your work on the `HtmlProcessor` could be quite handy.

**Comment by davydotcom** [comment]
I'm really not sure why you would need to turn off relative url replacement as this only works if it detects the file and still maintains its final relative path. We have never had to turn this off for third party CSS files

**Comment by rgoldberg** [comment]
I've forked both asset-pipeline & asset-pipeline-core.

I'm gonna start to commit to my forks & submit pull requests.

I've never forked or submitted pull requests before.

Also, I haven't really used Git beyond downloading third-party code (I've been using Mercurial for my own code).

I apologize in advance if I somehow mess up standard operating procedures.

Please tell me if I should change any procedures that I follow.

I'm planning on making a separate branch per fixed issue.  I'll create an issue in the correct repo, and try to associate my pull request with that issue.

If an issue requires code changes to both the plugin & core, should I create an issue in each project, and somehow link them in github?

Any other recommendations?

Thanks.

**Comment by davydotcom** [comment]
Going to close this due to new PRs coming in which are very much appreciated
